### ISSUE TITLE
dupl command line seems wrong

### ISSUE THREAD

**Issue by cep21** [alecthomas/gometalinter#32] opened 2015-09-23 17:15 UTC
Running gometalinter produces no results for dupl.

When I run with ```-v``` I see ```linting with dupl: dupl -plumbing -threshold {duplthreshold} {path}/*.go (on .)```

If I run on the command line ```dupl -plumbing -threshold 50 ./*.go``` I see no results.

However, if I run the command ```dupl -plumbing -threshold 50 .``` I see two results in different files.

I think the correct dupl command to run is ```dupl -plumbing -threshold 50 .```

**Comment by alecthomas** [comment] 2015-09-23 22:58
Running with . causes dupe to recurse all directories. ./*.go constrains it to a single directory. This is by design.

Ideally if you then ran gometalinter ./... it would run dupl once recursively, but that would require two commands for each tool.

**Comment by alecthomas** [comment] 2015-09-23 22:59
Running with . causes dupe to recurse all directories. ./*.go constrains it to a single directory. This is by design.

Ideally if you then ran gometalinter ./... it would run dupl once recursively, but that would require two commands for each tool.it would also mean relying on the spotty support for recursing the various tools provide.

**Comment by cep21** [comment] 2015-09-23 23:08
It is unfortunate that the two listed behaviors are different.  It's already less than idea that gometalinter cannot detect duplicate code across directories.  Ideally it would find the directories gometalinter is responsible for and pass them all to dupl.

I've filed https://github.com/mibk/dupl/issues/7 for this specific dupl issue.

**Comment by alecthomas** [comment] 2015-09-23 23:42
I swear this used to work. A test suite would be useful here.

**Comment by alecthomas** [comment] 2015-09-24 04:25
I added some integration tests to catch issues like this and the ineffassign one in the future. I'm going to close this for now, but feel free to open a new ticket for supporting checkers that can check across multiple packages.

**Closed by alecthomas** 2015-09-24 04:25 UTC
