### ISSUE TITLE
--vendor flag doesn't ignore whole vendor projects

### ISSUE THREAD

**Issue by zhaohaidao** [alecthomas/gometalinter#524] opened 2018-09-03 09:42 UTC
It is weird as only some files are detected.

### Debug output
[lint.txt](https://github.com/alecthomas/gometalinter/files/2345028/lint.txt)

**Comment by alecthomas** [comment] 2018-09-06 00:36
Duplicate of #449.

**Closed by alecthomas** 2018-09-06 00:36 UTC
