### ISSUE TITLE
gotype gone absolutely haywire

### ISSUE THREAD

**Issue by krancour** [alecthomas/gometalinter#357] opened 2017-09-26 19:35 UTC
Ever since 3eeb3c6358a5df7222c6a7f759554cc0f9729d7b, code that was flawlessly passing the gotype linter is having hundreds of issues found by that linter. Most prominent among them are imports not found (vendored code _and_ application source code) and undeclared names.

Unfortunately, I'm not at liberty to share the code or the traces.

**Comment by dnephin** [comment] 2017-09-26 19:52
Duplicate of #355 ? Want to try out #356 ?

Are the errors from directories that use multiple packages?

**Comment by alecthomas** [comment] 2017-09-28 00:18
Can you try master? We just merged a fix by @dnephin .

**Comment by krancour** [comment] 2017-09-28 16:40
Much better.

**Closed** 2017-09-28 16:40 UTC
